<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYYL40pT\AdminKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYYL40pT/AdminKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYYL40pT.legacy');

    return;
}

if (!\class_exists(AdminKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYYL40pT\AdminKernelDevDebugContainer::class, AdminKernelDevDebugContainer::class, false);
}

return new \ContainerYYL40pT\AdminKernelDevDebugContainer([
    'container.build_hash' => 'YYL40pT',
    'container.build_id' => 'c3a7ed65',
    'container.build_time' => 1767170416,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYYL40pT');
