<?php

namespace ContainerYYL40pT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsCheckout_ModuleService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'ps_checkout.module' shared service.
     *
     * @return \ps_checkout
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['ps_checkout.module'] = \Module::getInstanceByName('ps_checkout');
    }
}
