<?php

namespace ContainerPx8z9WS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeFormDataProviderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\AttributeFormDataProvider' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\AttributeFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.query_bus'] ?? $container->load('getPrestashop_Core_QueryBusService'));

        if (isset($container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\AttributeFormDataProvider'])) {
            return $container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\AttributeFormDataProvider'];
        }
        $b = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

        if (isset($container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\AttributeFormDataProvider'])) {
            return $container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\AttributeFormDataProvider'];
        }

        return $container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\AttributeFormDataProvider'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\AttributeFormDataProvider($a, $b, ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)));
    }
}
