<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKcwrxM\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKcwrxM/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNKcwrxM.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerNKcwrxM\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerNKcwrxM\AdminKernelProdContainer([
    'container.build_hash' => 'NKcwrxM',
    'container.build_id' => '919675db',
    'container.build_time' => 1767170408,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKcwrxM');
